# -*- coding: utf-8 -*-
"""HSDPP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y2q5ea7lM1Kl047bxkCrz_OSV0bt1yCe
"""

# !pip install googletrans
!pip install tweet-preprocessor

import pandas as pd
import preprocessor as p
tweetslist =[]
# tw='Dear @NawazSharifMNS please impose ban khawaja sb tweets after 9 PM for reasons…. https://t.co/PWsI4Lcnaa'
# p.set_options(p.OPT.URL, p.OPT.EMOJI,p.OPT.HASHTAG)
# a=p.clean(tw)
# print(a)

"""**Preprossing for Links remove and cleaning**"""

data=pd.read_csv('/content/drive/MyDrive/tw.csv')
for x in range(len(data)):
  tw = data.Tweet[x]
  # print(tw)
  p.set_options(p.OPT.URL, p.OPT.EMOJI,p.OPT.HASHTAG,p.OPT.NUMBER,p.OPT.EMOJI)
  clean_tw=p.clean(tw)
  print(clean_tw)

  # data saving
  tweets = {
         'tweet':clean_tw,
  }
  tweetslist.append(tweets)
  print ('tweet added', x)

  eu = pd.DataFrame(tweetslist)
  eu.to_csv('tweetslist.csv', index=False)

"""**Translation**"""

from googletrans import Translator

translator = Translator()
translated = translator.translate('Бороди́нское сраже́ние')

print(translated.text)

data.head()